version: '3.6'
services:
        db:
                image: postgres:14-alpine
                ports:
                        - '5434:5434'
                environment:
                      -  POSTGRES_USER=postgres
                      -  POSTGRES_PASSWORD=postgres
